#!/bin/sh

# PROVIDE: prd
# REQUIRE: NETWORKING netif
# KEYWORD: shutdown

. /etc/rc.subr

name="prd"
rcvar="${name}_enable"

command="/usr/sbin/daemon"
procname="/usr/local/sbin/${name}"
pidfile="/var/run/${name}.pid"

load_rc_config "$name"

: ${prd_enable:=NO}
: ${prd_flags:=""}
: ${prd_envfile:=""}

prd_load_env()
{
    if [ -n "$prd_envfile" ] && [ -r "$prd_envfile" ]; then
        set -a
        . "$prd_envfile"
        set +a
    fi
}

start_precmd="prd_load_env"

command_args="-p ${pidfile} -u _${name} -o /var/log/${name}.log -m 3 -- ${procname} ${prd_flags}"

run_rc_command "$1"

