#!/bin/sh

# PROVIDE: prj
# REQUIRE: DAEMON NETWORKING
# KEYWORD: shutdown

. /etc/rc.subr

name="prj"
rcvar="${name}_enable"

command="/usr/sbin/daemon"
procname="/usr/local/sbin/${name}"
pidfile="/var/run/${name}.pid"

# command_args="-p ${pidfile} -u _${name} -o /var/log/${name}.log -m 3 ${prj_env:+/usr/bin/env ${prj_env}} -- ${procname} ${prj_flags}"
command_args="-p ${pidfile} -u _${name} -o /var/log/${name}.log -m 3 -- /usr/bin/env ${prj_env} ${procname} ${prj_flags}"


load_rc_config $name

: ${prj_enable:=NO}
: ${prj_flags:=""}

run_rc_command "$1"

