#!/bin/sh

# PROVIDE: prj
# REQUIRE: NETWORKING netif
# KEYWORD: shutdown

. /etc/rc.subr

name="prj"
rcvar="${name}_enable"

command="/usr/sbin/daemon"
procname="/usr/local/sbin/${name}"
pidfile="/var/run/${name}.pid"

load_rc_config "$name"

: ${prj_enable:=NO}
: ${prj_flags:=""}
: ${prj_envfile:=""}

prj_load_env()
{
    if [ -n "$prj_envfile" ] && [ -r "$prj_envfile" ]; then
        set -a
        . "$prj_envfile"
        set +a
    fi
}

start_precmd="prj_load_env"

command_args="-p ${pidfile} -u _${name} -o /var/log/${name}.log -m 3 -- ${procname} ${prj_flags}"

run_rc_command "$1"
